# SonarCloud configuration
sonar.organization=ulruchdev
sonar.projectKey=gestion_de_stok_multifiliale
sonar.host.url=https://sonarcloud.io
sonar.projectName=gestion_de_stok_multifiliale

# Sources and tests
sonar.sources=stockmaster-shared/src/main/java,stockmaster-auth/src/main/java,stockmaster-groupe/src/main/java,stockmaster-utilisateur/src/main/java,stockmaster-catalogue/src/main/java,stockmaster-tiers/src/main/java,stockmaster-achat/src/main/java,stockmaster-stock/src/main/java,stockmaster-vente/src/main/java,stockmaster-notification/src/main/java,stockmaster-reporting/src/main/java
sonar.tests=stockmaster-shared/src/test/java,stockmaster-auth/src/test/java

# JaCoCo coverage
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=**/target/surefire-reports

# Exclusion des tests et des DTO (auto-générés par MapStruct)
sonar.exclusions=**/dto/**,**/mapper/**

# Java version
sonar.java.source=21
sonar.java.target=21

# Quality gate
sonar.qualitygate.wait=true
