# SonarCloud configuration
sonar.organization=ulruchdev
sonar.projectKey=gestion_de_stok_multifiliale
sonar.host.url=https://sonarcloud.io
sonar.projectName=gestion_de_stok_multifiliale

# Sources and tests
sonar.sources=backend/stockmaster-shared/src/main/java,backend/stockmaster-auth/src/main/java,backend/stockmaster-groupe/src/main/java,backend/stockmaster-utilisateur/src/main/java,backend/stockmaster-catalogue/src/main/java,backend/stockmaster-tiers/src/main/java,backend/stockmaster-achat/src/main/java,backend/stockmaster-stock/src/main/java,backend/stockmaster-vente/src/main/java,backend/stockmaster-notification/src/main/java,backend/stockmaster-reporting/src/main/java
sonar.tests=backend/stockmaster-shared/src/test/java,backend/stockmaster-auth/src/test/java

# JaCoCo coverage
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=**/target/surefire-reports

# Exclusion des tests, DTO (auto-générés par MapStruct) et migrations Flyway
sonar.exclusions=**/dto/**,**/mapper/**,**/db/migration/**
sonar.coverage.exclusions=**/config/**,**/dto/**,**/db/migration/**

# Java version
sonar.java.source=21
sonar.java.target=21

# Quality gate
sonar.qualitygate.wait=true
